const menu = [
    {
      id: 1,
      title: 'buttermilk pancakes',
      category: 'breakfast',
      price: 15.99,
      img: 'https://food.fnr.sndimg.com/content/dam/images/food/fullset/2019/7/11/0/FNK_the-best-pancakes_H_s4x3.jpg.rend.hgtvcom.616.462.suffix/1562853903667.jpeg',
      desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
    },
    {
      id: 2,
      title: 'diner double',
      category: 'lunch',
      price: 13.99,
      img: 'https://www.shutterstock.com/image-photo/iconic-diner-double-cheeseburger-stacked-260nw-694423843.jpg',
      desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
    },
    {
      id: 3,
      title: 'godzilla milkshake',
      category: 'shakes',
      price: 6.99,
      img: 'https://i2-prod.glasgowlive.co.uk/incoming/article16335485.ece/ALTERNATES/s615b/0_DSC_5315.jpg',
      desc: `ombucha chillwave fanny pack 3 wolf moon street art photo booth before they sold out organic viral.`,
    },
    {
      id: 4,
      title: 'country delight',
      category: 'breakfast',
      price: 20.99,
      img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTdWpQ109BBFO1VOpkW2PD6PD6cryHbg_ZQJmajDNxLk6uPXrGd36WlA49KQi3GuHs2Ol4&usqp=CAU',
      desc: `Shabby chic keffiyeh neutra snackwave pork belly shoreditch. Prism austin mlkshk truffaut, `,
    },
    {
      id: 5,
      title: 'egg attack',
      category: 'lunch',
      price: 22.99,
      img: 'https://media-cldnry.s-nbcnews.com/image/upload/t_fit-1500w,f_auto,q_auto:best/newscms/2018_38/1368436/eggs-today-main-180917.jpg',
      desc: `franzen vegan pabst bicycle rights kickstarter pinterest meditation farm-to-table 90's pop-up `,
    },
    {
      id: 6,
      title: 'oreo dream',
      category: 'shakes',
      price: 18.99,
      img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRRnD3FjYkAu7dvUsjgN_CCkYQ8MpMSL5t9cw&usqp=CAU',
      desc: `Portland chicharrones ethical edison bulb, palo santo craft beer chia heirloom iPhone everyday`,
    },
    {
      id: 7,
      title: 'bacon overflow',
      category: 'breakfast',
      price: 8.99,
      img: 'https://external-preview.redd.it/H5wUsbQwYSKQYxJII7ARXb6Jvk_-Xb30tyjbwf_MuZU.jpg?auto=webp&s=dd43553dc06d9f6d229663c7160282f42b47a539',
      desc: `carry jianbing normcore freegan. Viral single-origin coffee live-edge, pork belly cloud bread iceland put a bird `,
    },
    {
      id: 8,
      title: 'american classic',
      category: 'lunch',
      price: 12.99,
      img: 'https://7esl.com/wp-content/uploads/2022/08/Fried-Chicken.jpg',
      desc: `on it tumblr kickstarter thundercats migas everyday carry squid palo santo leggings. Food truck truffaut  `,
    },
    {
      id: 9,
      title: 'quarantine buddy',
      category: 'shakes',
      price: 16.99,
      img: 'https://assets.bonappetit.com/photos/5f331215cef63982207a3eab/master/w_1600%2Cc_limit/Short-Stories-Curry-Night-Restaurant-Diaries.jpg',
      desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
    },
  ];
  export default menu;